name: Deploy
on:
  push:
    branches:
      - main

env:
  MISE_EXPERIMENTAL: "1"
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  GITHUB_TOKEN: ${{ secrets.PEPICRFT_GITHUB_TOKEN }}

jobs:
  cloudflare:
    name: Cloudflare
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/jdx/mise-action@v2
        with:
          cache: true
      - run: mise run deploy
