name: Deploy
on:
  push:
    branches:
      - main

jobs:
  cloudflare:
    name: Cloudflare
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/logseq/publish-spa@main
