name: Deploy
on:
  push:
    branches:
      - main

env:
  MISE_EXPERIMENTAL: "1"
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  MISE_GITHUB_TOKEN: ${{ secrets.PEPICRFT_GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PEPICRFT_GITHUB_TOKEN }}

jobs:
  cloudflare:
    name: Cloudflare
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - uses: logseq/publish-spa@main
        with:
          output-directory: build
          version: nightly
      - run: mise run deploy
